algorandfoundation/puya

pyproject.toml
src/puya/ir/models.py
src/puya/ir/optimize/constant_propagation.py
src/puyapy-stubs/_primitives.pyi

- fix bug in constant propagation with duplicate target blocks
- fix bug in IR validation of switch, where atype was compared with == instead of &
- remove floating dead comment
- manually bump version number

fix: resolves some bugs with match statements

---

poetry.lock
pyproject.toml

This allows PyTEAL and Puya to be installed in the same venv for now, for those looking to test it out that way in their existing projects.

fix: relax docstring-parser version constraint for now

---

src/puya/ir/optimize/constant_propagation.py

make IntrinsicSimplifier more type safe and clarify why there's slightly different handling of select-with-const-condition inlining

minor IntrinsicSimplifier refactor

---

src/puya/awst_build/subroutine.py
src/puya/awst_build/validation/arc4_copy.py
tests/test_execution.py
tests/test_expected_output/arc4.test
tests/test_expected_output/data.py

fix: Flip the arc4 copy logc so we look for specific nodes rather than exclude an ever growing list of 'safe' nodes

---

CHANGELOG.md
poetry.lock
pyproject.toml
templates/CHANGELOG.md.j2

Manually curate changelog for v2.0.0, and prevent it from being overwritten on future releases.
Also update semantic-release to v9.5

Changelog changes

---

README.md

Give more emphasis to the recommended quick start installation approach in the README.
In the previous layout, the manual approach draws the attention due to the numbered list and the code block (vs. an inline code block in the first sentence)
In an attempt to make this more visible, I propose separating the installation instructions into two sections, and move the usage/compile instructions to a separate section.
- README.md restructure for emphasis on recommended quickstart approach and clarity

README.md: make Quick Start more prominent, separate Usage from Installation

---

stubs/pyproject.toml

A consequence of changing the stubs build backend to hatch is that poetry project still used by the puya compiler itself can no longer add the stubs as a dev dependency. So this breaks mypy type checking. Work around for now is to revert stubs project back to using poetry.
Better solution will be to switch both puya and stubs to use hatch

Switch stubs project build backend back to poetry

---

src/puya/awst/function_traverser.py
src/puya/awst/nodes.py
src/puya/awst/to_code_visitor.py
src/puya/awst/visitors.py
src/puya/ir/builder/main.py

- Adds support for `i++` and `i--` expressions on uint64 and biguint types

feature: Include postfix unary operations for uint64 and biguint

---

stubs/algopy-stubs/_reference.pyi

- Minor typo in return type of total_num_byte_slice on Account stub

fix: change total_num_byte_slice return type to UInt64

---

src/puya/awst/nodes.py
src/puya/awst/to_code_visitor.py
src/puya/awst/visitors.py
src/puya/awst_build/eb/storage/_common.py
src/puya/awst_build/eb/storage/global_state.py
src/puya/awst_build/eb/storage/local_state.py
src/puya/ir/builder/main.py
src/puya/ir/builder/storage.py

- Change StateDelete node to be an expression rather than statement as not all user languages have a `delete` statement with applicable use to this scenario

refactor: Change StateDelete node to be an expression

---

stubs/algopy-stubs/arc4.pyi
stubs/pyproject.toml

This is a bug-fix (stubs don't accurately reflect what is supported) thus only a patch-level version bump.

fix: remove `slice` from `__getitem__` in `algopy.arc4.DynamicArray` and `algopy.arc4.StaticArray`

---

.github/workflows/cd.yaml
.github/workflows/check-python.yaml
.github/workflows/gh-pages.yaml
test_cases/literals/puya.log

To get CI/CD working I've temporarily pinned all Actions to Python 3.12.6, apparently a deprecation warning has changed vs 3.12.5, which was included in an approval output. And Actions seems to have only been slowly upgrading each task (probably due to caching?) so output was inconsistent between checks. In general we want the latest patch release, so once that change settles we should remove the explicit patch version again.

temporarily pin to Python 3.12.6 in CI/CD to get consistent output behaviour

---

scripts/generate_docs.py
src/puyapy/awst_build/context.py
src/puyapy/awst_build/main.py
src/puyapy/compile.py
src/puyapy/parse.py
tests/test_expected_output/data.py
tests/test_transaction_fields.py
tests/utils/__init__.py

Refactor expected-output tests to execute in declared order within each `.test file` - useful when debugging.
As part of this, remove mypy BuildManager from ParseResult, which will prevent further coupling of mypy.

Make "expected output" tests execute in order within each `.test` file

---

src/puya/awst/nodes.py

- Removes the constraint on AssignmentExpression.target preventing tuple expressions. These are not allowed in python but are in TypeScript

Remove restriction on using tuple expressions for assignment expressions as TypeScript allows this

---

.github/workflows/cd.yaml
.github/workflows/check-python.yaml
.github/workflows/gh-pages.yaml

revert temporary pinning of Python to 3.12.6 in CI/CD now that GitHub runners appear to have been updated

unpin Python CI/CD version

---

src/puyapy/__main__.py

- As part of the puya debugging outcome, output source maps flag was introduced with default value set to False. Now that the extension with latest puya sourcemaps is ready for release - this pr re introduces default True value set to the sourcemaps. This is also to unblock generic uses of newer AVM Debugger Extension with existing v6  (utils ts ) and v2 (utils-py) packages on algorand python template. Utils ts v7, ts-debug and debug related utils-py changes along with updates in python template are to be shipped later in coming weeks (as soon as v7 of utils-ts is published on npm).

chore: restoring output sourcemaps flag defaults to true

---

docs/architecture-decisions/2024-12-10_arrays.md

Collaboration with @daniel-makerx to create an Array ADR based on the discussions we've had thus far.

docs: add initial array adr

---

.github/workflows/cd.yaml
.github/workflows/check-python.yaml
.github/workflows/gh-pages.yaml

temporarily pinning poetry to `<2.0` until a release for poetry issue [#9961](https://github.com/python-poetry/poetry/issues/9961) is made

Pin poetry version to less than 2.0 in CI/CD

---

docs/index.md
docs/references/algopy_testing.md
docs/references/avm_debugger.md

- Adds reference to vscode debug extension
- Removes a note claiming that algopy testing is in preview (its now stable)

docs: add debugger ref; remove note from algopy testing doc as its no longer in preview

---

langspec.puya.json
scripts/transform_lang_spec.py
src/puya/ir/avm_ops.py
src/puyapy/awst_build/intrinsic_data.py
stubs/algopy-stubs/op.pyi
stubs/pyproject.toml

According to the [doc](https://github.com/algorand/go-algorand/blob/b2d41d0608b2a3e4c302df358950bdeb8b80be83/data/transactions/logic/TEAL_opcodes_v11.md#voter_params_get), the stack arg `A` of `voter_params_get` op code is an Account which is the same as the stack arg `A` of `acct_params_get` op code. 
This PR changes the type of parameter `a` for the methods of `VoterParamsGet` class to be `Account | UInt64 | int` to be inline with `AcctParamsGet` class.

fix: accept address or index param for VoterParamsGet methods

---

README.md
changelog.d/20250422_104915_bobby.lat_default_arc56.md
docs/compiler.md
docs/index.md
docs/lg-calling-apps.md
docs/lg-storage.md
docs/lg-structure.md
scripts/compile_all_examples.py
src/puyapy/__main__.py
tests/test_cli.py

- produce ARC56 app spec artefact by default when compiling
- also, produce ARC32 app spec artefact by default when compiling (existing behaviour)

feat: generate arc56 app spec by default

---

src/puya/awst/visitors.py
src/puya/awst/wtypes.py
src/puya/ir/_arc4_default_args.py
src/puya/ir/_contract_metadata.py
src/puya/ir/arc4_types.py
src/puya/ir/builder/arc4.py
src/puyapy/awst_build/arc4_utils.py
tests/test_arc4_codec.py
tests/test_expected_output/arc4.test

This change removes the required field `arc4_name` from `wtypes.ARC4Type`. For ARC-4 aggregate types (e.g. `arc4.DynamicArray`, `arc4.Struct`), this allows deferring the conversion from native to ARC-4 types until the IR layer. This is a step towards allowing native types inside ARC-4 aggregates to be handled transparently.

refactor: remove arc4_name from wtypes.ARC4Type

---

src/puya/awst/wtypes.py

Turns out `cattrs` doesn't use alias for serialisation by default, so this attempt to not break serialisation for `puya-ts` was useless

refactor: remove alias on `ARC4Type.arc4_alias` field

---

src/puya/awst/function_traverser.py
src/puya/awst/nodes.py
src/puya/awst/to_code_visitor.py
src/puya/awst/visitors.py
src/puya/ir/builder/itxn.py
src/puya/ir/builder/main.py
tests/from_awst/itxn_compose/module.awst.json
tests/from_awst/itxn_compose/out/ItxnComposeAlgo.approval.teal
tests/from_awst/itxn_compose/out/ItxnComposeAlgo.arc32.json
tests/from_awst/itxn_compose/out/ItxnComposeAlgo.clear.teal
tests/from_awst/itxn_compose/out/ItxnComposeAlgo.ir/ItxnComposeAlgo.approval.0.destructured.ir
tests/from_awst/itxn_compose/out/ItxnComposeAlgo.ir/ItxnComposeAlgo.clear.0.destructured.ir
tests/from_awst/itxn_compose/out/VerifierContract.approval.teal
tests/from_awst/itxn_compose/out/VerifierContract.arc32.json
tests/from_awst/itxn_compose/out/VerifierContract.clear.teal
tests/from_awst/itxn_compose/out/VerifierContract.ir/VerifierContract.approval.0.destructured.ir
tests/from_awst/itxn_compose/out/VerifierContract.ir/VerifierContract.clear.0.destructured.ir
tests/from_awst/itxn_compose/test_itxn_compose.py
tests/from_awst/static_bytes/test_static_bytes.py
tests/from_awst/util.py
tests/output/nodes.ts.txt

- Add SetInnerTransactionFields node which abstracts em…ission of `itxn_field` ops for a sequence of WinnerTransactionFields expressions delimited with `itxn_begin` or `itxn_next` ops.

feat(internal): Add SetInnerTransactionFields node 

---

src/puya/__main__.py
src/puya/awst/nodes.py
src/puya/awst/serialize.py
src/puya/service.py

1) When running puya in service mode (currently used by both LSP and soon to also be used by puya-ts in CLI compilations also), leave the "feature" request params in their raw serialized format, and only deserialize ("structure" in cattrs) once we're inside the handler.
By doing so, we can both capture and report any error messages, which means the client has that information and can report it, and also that it's not left waiting for a response that never arrives.
2) Don't raise builtin exceptions in AWST node validation, prefer to either log (if we can continue without introducing spurious errors later on by doing so), or raise an exception derived from PuyaError and thus retain the source location
3) Improve error logging when an exception occurs during deserialization:
- Disable …

Deserialization error handling
